package com.nagarro.qathon.exceptionHandler.domain;

public class UserFoundException extends Exception {
    public UserFoundException(String message) {
        super(message);
    }
}


